on:
    workflow_dispatch:
    push:
    pull_request:
      paths:
        - ec2.tf
        - provider.tf
        - .github/workflows/aws.yml

name: AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1

        - run: aws ec2 describe-instances

        - run: terraform version
        - run: terraform fmt -recursive -check
        - run: terraform init
        - run: terraform validate
        - run: terraform plan
        - run: terraform apply -auto-approve
        - run: git status
